version: '2'
services:
  redis:
    image: redis
    container_name: redis
    networks:
      - default
    volumes:
      - redis:/data
    command: [redis-server, --appendonly, "yes"]
  hipache:
    build: hipache
    container_name: hipache
    networks:
      - default
      - proxy 
    ports:
      - 80:80
volumes:
  redis: ~
networks:
  proxy:
    external: true
  default:
    driver_opts:
      com.docker.network.bridge.name: br-hipache
